MONGO:
  URI-MODE: true
  NORMAL:
    HOST: 127.0.0.1
    PORT: 27017
    DATABASE: Array
    AUTHENTICATION:
      ENABLED: false
      USERNAME: ''
      PASSWORD: ''
  URI:
    DATABASE: PotPvPRP
    CONNECTION_STRING: mongodb://127.0.0.1:27017/PotPvPRP